name: Build & Push Docker image to Docker Hub (Dev branch)

on:
  push:
    branches: [dev]
  workflow_dispatch:

jobs:
  build-and-push-dev:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4.2.2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.11.1

      - name: Log in to Docker Hub
        uses: docker/login-action@v3.4.0
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build & Push to Docker Hub
        id: build-and-push
        env:
          IMAGE_TAG: dev-${{ github.run_number }}
        run: |
          echo "Building and pushing tags: latest and $IMAGE_TAG"

          docker buildx build \
            --platform linux/amd64,linux/arm64 \
            --push \
            --cache-from=type=gha \
            --cache-to=type=gha,mode=max \
            -t ciuse99/mediaflowrr:${IMAGE_TAG} .

      - name: Image digest
        run: echo "Pushed digest ${{ steps.build-and-push.outputs.digest }}"
